= Kotlin EE: Boost your Productivity with Kotlin, Jakarta EE and Docker

https://wikipedia.org/wiki/Kotlin_(programming_language)[Kotlin] is a language for the https://wikipedia.org/wiki/Java_virtual_machine[JVM], invented by https://wikipedia.org/wiki/JetBrains[JetBrains] a few years ago. But what the hell is Kotlin EE? If you never heard of Kotlin EE, don't panic, it does not exist. But you can use it right away and boost your productivity!

I invented the term Kotlin EE as a synonym for using the Kotlin language together with the Jakarta EE (former known as Java EE) API to create services of any size (microservices, nanoservices etc.) with just a few lines of code and the ability to focus on the business logic.

Kotlin and Jakarta EE are a perfect couple for writing micro- or nanoservices. Kotlin is a very pragmatic language, builds on many concepts and techniques from Java, designed for developer productivity. Kotlin works great with all existing Java libraries and frameworks and runs with the same level of performance as Java.

The Jakarta EE API allows us to code against a proven and stable API. Provided libraries like JAX-RS for writing RESTful APIs and Jackson for JSON (de)serializing decrease the need for additional third-party libraries which results in a short build time and a small artifact size. Benefit from a very fast build and test feedback and stay focused on your code.

In this talk, I try to prove my statements from above. Live on stage I write a service in Kotlin with a RESTful JSON API with only a few lines of code and run the service using a local Docker cloud where you can see how these can be scaled up and down to manage fluctuating loads. Coding, building, testing, deploying, scaling: fast and efficient!
